In [1]:
import numpy as np
from keras.datasets import mnist
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import cv2

Using TensorFlow backend.


In [2]:
#scalar(0D tensors) dimension also called axis
a = np.array(10) # can't put more numbers into the '()' !
print(a, type(a))
print("dimension: ", a.ndim)

10 <class 'numpy.ndarray'>
dimension:  0


In [3]:
#vector(1D tensors)
b = np.array([1,2,3]) # it's a 3D vector or to say a 1D vector!!
print(b, type(b))
print("dimension(axis): ",b.ndim)
print("shape: ", b.shape)

[1 2 3] <class 'numpy.ndarray'>
dimension(axis):  1
shape:  (3,)


In [4]:
# matrices(2D tensors)
c = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
print(c)
print("rank: ", c.ndim)
print("shape: ", c.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rank:  2
shape:  (3, 4)


In [5]:
#3D tensors
d = np.array([
    [[1,-2,3],
    [3,2,1]],
    [[4,5,6],
    [6,5,4]],
    [[-10,8,9],
    [9,8,7]],
    [[1,1,1],
    [0,0,0]]
])
print(d)
print("rank: ", d.ndim)
print("shape: ", d.shape)

[[[  1  -2   3]
  [  3   2   1]]

 [[  4   5   6]
  [  6   5   4]]

 [[-10   8   9]
  [  9   8   7]]

 [[  1   1   1]
  [  0   0   0]]]
rank:  3
shape:  (4, 2, 3)


In [6]:
d.shape[0]

4

In [7]:
np.maximum(d, 0) # what relu actually do !!

array([[[1, 0, 3],
        [3, 2, 1]],

       [[4, 5, 6],
        [6, 5, 4]],

       [[0, 8, 9],
        [9, 8, 7]],

       [[1, 1, 1],
        [0, 0, 0]]])

In [8]:
#4D tensors
e = np.array([
    [[[1,2,3],
     [4,5,6]],
    [[3,2,1],
    [6,5,4]],
    [[0,0,0],
    [1,1,1]],
    [[7,7,7],
    [8,8,8]]],
    
    [[[-1,-1,-1],
     [2,2,2]],
    [[3,3,3],
    [4,4,4]],
    [[5,5,5],
    [6,6,6]],
    [[9,9,9],
    [7,7,7]]]
])
print(e)
print("rank: ", e.ndim)
print("shape: ", e.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 3  2  1]
   [ 6  5  4]]

  [[ 0  0  0]
   [ 1  1  1]]

  [[ 7  7  7]
   [ 8  8  8]]]


 [[[-1 -1 -1]
   [ 2  2  2]]

  [[ 3  3  3]
   [ 4  4  4]]

  [[ 5  5  5]
   [ 6  6  6]]

  [[ 9  9  9]
   [ 7  7  7]]]]
rank:  4
shape:  (2, 4, 2, 3)


In [9]:
e2 = np.array([
    [[[[1,2,3],
     [4,5,6]],
    [[3,2,1],
    [6,5,4]],
    [[0,0,0],
    [1,1,1]],
    [[7,7,7],
    [8,8,8]]]],
    
])
print(e2)
print("rank: ", e2.ndim)
print("shape: ", e2.shape)

[[[[[1 2 3]
    [4 5 6]]

   [[3 2 1]
    [6 5 4]]

   [[0 0 0]
    [1 1 1]]

   [[7 7 7]
    [8 8 8]]]]]
rank:  5
shape:  (1, 1, 4, 2, 3)


In [10]:
print(len(e))
f = e[0]
print(f)
print("rank: ", f.ndim)
print("shape: ", f.shape)

2
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]

 [[0 0 0]
  [1 1 1]]

 [[7 7 7]
  [8 8 8]]]
rank:  3
shape:  (4, 2, 3)
